import "./globals.css";
import Navbar from "@/components/Utilities/Navbar";
import Footer from "@/components/Footer";
import Sponsor from "@/components/Sponsor";

export const metadata = {
  title: "Kelfast",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Sponsor />
        <Footer />
      </body>
    </html>
  );
}
